sudo: true
language: java
jdk:
- oraclejdk8
script:
- mvn clean install spring-boot:repackage
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: motion-project
  api_key:
    secure: oV7a5Pb6tUkJEEYwmHUATK8BJMAcdINOrytG+QByzopDlStp3Umvt+O6HJk7SHP7CMMVdHFTg076ZpxKJ5g+qFfzNfb0EMJI2DANUq2pF8GpJugFedOqf0TvDVRqrLpIVaoBdRqdApCZ1iLNBc3ElgBj2MfCKniOw9um5q4+I9UuLnYjvSWzyK9eBCKyNoVOQMAql3216H5JfQ0I6mM9bKJRyg7Tvn2Q//YzTKbX6EYUuIQqKT6vtAFmSHRNBXH9rxR2iYDPg1kNwM4tSTR8JfLW0NdVoqghgMhHe2VePMFq62Vpu7URg6lYCbNshFDJQidgGlXsqf6IkBtKFWkK1h4GTfOpf4Tg2O6GsdEDVyyFF6y6NH98UA/rZetBjmuLcV6MBbo4iEqL00rfn1qIF+OeMOuVHY/FNQZrWDt0z2a5jmAeFWSFmyNNhPAIdvE02z3JsKT9kb6xAzz27A5hLE9uNW2Rcs4A1tRvinauvblNwe33Rvots6+K+W3yDbXlBdo0iCJjjClLmKIisluq92ltWwUyFVHN08e5ZgXE2T/zHlcij0wOBa0uUgti29oYECQ+1kotfqo06xXEADx8XaACvc8nxQfRiBfRLeYV+0vvONz5pnkuyVcOX2xy2osC71lWlLKJMhAA3LzGF1fFqDOARVXqgcQfiKE6qz+HDiY=
