sudo: true
language: java
jdk:
- oraclejdk8
script:
- mvn clean install spring-boot:repackage
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: motion-project
  api_key:
    secure: GkYaVBO+1ggX/UKYHLdpWxgWocAppvmHSkqTzCXjs3IMSfGutAwmomuWDnB3lyB+zC9Ee0U6StfCxH2IdJIcLkWM5gvjvSKU1KAPhsZi/vLVYuWkS5/AvsHwlFMA1tzxCMQXOGUZPlOa9bWNyrWhAg7JmkvJ34xLzSUbDsYiJuNWGGbexTzNiie/ID6/oJ04vVAB9PoipGbwDHZ//QQzoNq/DfcOCI5xCIhYD2Kc3JbWr/7tVMyVFrUZQTmJGqqVRBk8897CIy9VlwgA1Qqy+V3WvJB2kzyYtgZnlPTONdNnMkIeOW+7OTAGMxBF+KfllLUXfl6jmv9hyvgZXgfEztK2cMKMZepTiRZfCAOkWANin6CHGD35KrPYSm+SPaPooH8zqopob7AptK4QEUl24pTHKpR1cYxEks3hdi297l/7Q9k2qNOebH54fciXeBpeGSekcNBKknOQa0YOd1bBu18QQutVfgWVpWOo+MebfJwXVxzwEBLTrHTgiD3QI3g9g1pg0ORzaxylylcszo5+kJRslMuAPPYfEIIq8ODNcXIM+16JlU5Xtft2BW/TQXhR/tJFF2RHVG6goAhwaSpR/Fb2XkU2WDduwY0FuNXJ9irNtdJ9+wDUlR0sS4Lvrm2p8uwyktV5DGKIPgu7OAJbP4k1MQlu9gIqZbwrzUmt+5c=
